#!/bin/sh
#
# $Id: hb,v 1.11 2008/11/26 17:09:15 bus Exp bus $
#

# Output parameters and exit to avoid recursion when scaffolding
if [ -n "$scaffolding" ]; then
	echo "dvd_source=\"$dvd_source\""
	echo "output=\"$output\""
	echo "audio_tracks=\"$audio_tracks\""
	echo "audio_encoder=\"$audio_encoder\""
	echo "audio_bitrate=\"$audio_bitrate\""
	echo "subtitles=\"$subtitles\""
	echo "quality=\"$quality\""
	echo "anamorphic=\"$anamorphic\""
	echo "anamorphic_style=\"$anamorphic_style\""
	echo "title=\"$title\""
	echo "chapters=\"$chapters\""
	echo "grayscale=\"$grayscale\""
	echo "x264_filter_options=\"$x264_filter_options\""
	echo "x264_nr_options=\"$x264_nr_options\""
	echo "deinterlace=\"$deinterlace\""
	echo "deinterlace_params=\"$deinterlace_params\""
	echo "decomb=\"$decomb\""
	echo "decomb_params=\"$decomb_params\""
	exit
fi

# This is the version of the configuration file.  Bump this every time there's
# a change to the default configuration that would justify a configuration
# regeneration in existing projects.
hb_config_version='5'

# Scaffold
if [ $0 = '../../etc/hb' ]; then
	scaffolding='1'
	echo -n 'Scaffolding'

	# Defaults
	dvd_source=''
	output=''
	audio_tracks='1'
	audio_encoder='ac3'
	audio_bitrate='160'
	subtitles=''
	quality='0.66'
	anamorphic='Yes'
	anamorphic_style='strict'
	title='1'
	chapters='all'
	grayscale='No'
	x264_filter_options='filter=-2,-1'
	x264_nr_options='nr=0'
	deinterlace=''
	deinterlace_params=''
	decomb='No'
	decomb_params=''

	# Make sure these variables are exported to run in order to set
	# defaults for variables not present and also pass along the
	# scaffolding variable.
	export scaffolding \
	       dvd_source \
	       output \
	       audio_tracks \
	       audio_encoder \
	       audio_bitrate \
	       subtitles \
	       quality \
	       anamorphic \
	       anamorphic_style \
	       title \
	       chapters \
	       grayscale \
	       x264_filter_options \
	       x264_nr_options \
	       deinterlace \
	       deinterlace_params \
	       decomb \
	       decomb_params

	if [ -r run ]; then
		echo ' with existing settings!!!'
		cp run run.old
		eval `sh ./run`
	else
		echo ' !!!'
	fi
	cat <<_EOF_ > run
#!/bin/sh

if [ -z "\$scaffolding" ]; then
	set -ex
fi

# Source footage.  Needs to be a directory, not a DVD device.
dvd_source='$dvd_source'

# Output filename.  Do not include a filename extension.
output='$output'

# Audio tracks to include.  [int space separated or none] Default: 1
audio_tracks='$audio_tracks'

# Audio encoder.  [faac/lame/vorbis/ac3] Default: ac3
# If you're including multiple audio tracks and want to use a different encoder
# for some of them, list the encoders you want to use space separated, ordered
# by the audio tracks you're including.
audio_encoder='$audio_encoder'

# Audio bitrate.  [int space separated or none] Default: 160
# If you're including multiple audio tracks and want to use a different bitrate
# for some of them, list the bitrates you want to use space separated, ordered
# by the audio tracks you're including.  This parameter is ignored if the track
# is ac3 passthrough, it is used for faac/lame/vorbis.
audio_bitrate='$audio_bitrate'

# Subtitles to include.  Default: none
subtitles='$subtitles'

# Video quality.  [0.0 - 1.0] Default: 0.66
quality='$quality'

# Anamorphic video?  [YES/NO/Yes/No/1/0] Default: Yes
anamorphic='$anamorphic'

# Anamorphic style?  [strict/loose] Default: strict
# See http://trac.handbrake.fr/wiki/AnamorphicGuide
anamorphic_style='$anamorphic_style'

# Title to work on.  Default: 1
title='$title'

# Chapters to work on.  Default: all
chapters='$chapters'

# Is your film is black and white?  [YES/NO/Yes/No/1/0] Default: No
# Setting this to Yes if your film is black and white can reduce green tinge or
# rainbow shimmering in black and white encodes.
grayscale='$grayscale'

# x264 filter parameters
# filter 0,0 for noisy or bad sources and -2,-1 for good sources. 
x264_filter_options='$x264_filter_options'

# x264 noise reduction parameters
# Use nr=0 for good sources. Max nr = 150.  If you use more it blocks more.
x264_nr_options='$x264_nr_options'

# Which deinterlacing filter to use?  [NO/No/adaptive/pullup]
deinterlace='$deinterlace'

# If you're using a deinterlacing filter (set above) you may set it's
# parameters here.
# adaptive YM:FD:MM:QP   default: 0:-1:-1:1
# pullup   L:R:T:B:SB:MP default: 1:1:4:4:0:0
deinterlace_params='$deinterlace_params'

# Selectively deinterlace frames when combing is detected (32detect).
# [YES/NO/Yes/No/1/0] Default: No
# This may be also combined with the deinterlacer to catch frames that slip
# through due to field editing and such.
decomb='$decomb'

# If you're using decomb (set above) you may set it's parameters here.
# MO:ME:MT:ST:BT:BX:BY default: 1:2:6:9:80:16:16
decomb_params='$decomb_params'

# Config version.  Don't mess with this
config_version='$hb_config_version'

. ../../etc/hb
_EOF_
	echo 'Done.'
	exit
fi

# Is config_version newer than what hb supports?
if [ -n "$config_version" -a $config_version -gt $hb_config_version ]; then
	set +x
	echo "This version of hb is too old to support your project's configuration" 1>&2
	echo "file.  I support version $hb_config_version, your configuration version is $config_version." 1>&2
	echo "Re-scaffolding your config will fix this, but you may lose features." 1>&2
	exit 1
fi

# Ensure input and output files are defined
if [ -z "$dvd_source" ]; then
	echo "ERROR: dvd_source is not defined." 1>&2
	exit 1
fi
if [ -z "$output" ]; then
	echo "ERROR: output is not defined." 1>&2
	exit 1
fi

# defaults
x264_options="
$x264_filter_options
$x264_nr_options
ref=4
mixed-refs
direct=auto
bframes=3
b-pyramid
weightb
subme=9
trellis=1
partitions=i8x8,p8x8,b8x8
8x8dct
me=umh
no-fast-pskip
no-dct-decimate
psy-rd=1.0:1.0"

test -z "$title" && title='1'
test -z "$audio_tracks" && audio_tracks='1'
test -z "$audio_encoder" && audio_encoder='ac3'
test -z "$audio_bitrate" && audio_bitrate='160'
test -z "$quality" && quality='0.66'

# Normalize
_x264_options=`echo $x264_options | sed 's/[ 	]\+/:/g'`
_audio_tracks=`echo $audio_tracks | sed 's/[    ]\+/,/g'`
_audio_encoder=`echo $audio_encoder | sed 's/[    ]\+/,/g'`
_audio_bitrate=`echo $audio_bitrate | sed 's/[    ]\+/,/g'`
test "$chapters" = 'all' && chapters=''

# Anamorphic?
case "$anamorphic" in
	[nN][oO])
	_anamorphic_arg=''
	anamorphic='No'
	;;
	0)
	_anamorphic_arg=''
	anamorphic='No'
	;;
	*)
	anamorphic='Yes'
	if [ -n "$anamorphic_style" -a "$anamorphic_style" = 'loose' ]; then
		_anamorphic_arg='-P'
		anamorphic_style='Loose'
	else
		_anamorphic_arg='-p'
		anamorphic_style='Strict'
	fi
	;;
esac

# build args
_chapter_arg=''
if [ -n "$chapters" ]; then
	_chapter_arg="-c $chapters"
fi

# Grayscale?
case "$grayscale" in
	[yY][eE][sS])
	_grayscale_arg='--grayscale'
	grayscale='Yes'
	;;
	1)
	_grayscale_arg='--grayscale'
	grayscale='Yes'
	;;
	*)
	grayscale='No'
	_grayscale_arg=''
	;;
esac

# Use mkv by default.  It supports everything.
output_format='mkv'

# Deinterlacing
case "$deinterlace" in
	adaptive)
	_deinterlace_arg='--deinterlace'
	;;
	pullup)
	_deinterlace_arg='--detelecine'
	;;
	*)
	_deinterlace_arg=''
	deinterlace='No'
	;;
esac

if [ "$deinterlace" != 'No' -a -n "$deinterlace_params" ]; then
	_deinterlace_arg="$_deinterlace_arg $deinterlace_params"
fi

# Decombing
case "$decomb" in
	[yY][eE][sS])
	_decomb_arg='--decomb'
	decomb='Yes'
	;;
	1)
	_decomb_arg='--decomb'
	decomb='Yes'
	;;
	*)
	_decomb_arg=''
	decomb='No'
	;;
esac

if [ "$decomb" != 'No' -a -n "$decomb_params" ]; then
	_decomb_arg="$_decomb_arg $decomb_params"
fi

set +x
echo
echo '*******************************************************************************'
echo "DVD source: $dvd_source"
echo "Output filename: ${output}.${output_format}"
echo "Audio tracks: $audio_tracks"
echo "Audio encoder: $audio_encoder"
echo "Audio bitrate: $audio_bitrate"
echo "Subtitles: $subtitles"
echo "Video quality: $quality"
echo "Anamorphic video: $anamorphic ($anamorphic_style)"
echo "Video title: $title"
if [ -n "$chapters" ]; then
	echo "Video chapters: $chapters"
fi
echo "Grayscale encoding: $grayscale"
echo "Deinterlace video: $deinterlace"
if [ "$deinterlace" != 'No' -a -n "$deinterlace_params" ]; then
	echo "Deinterlace params: $deinterlace_params"
fi
echo "Decomb video: $decomb"
if [ "$decomb" != 'No' -a -n "$decomb_params" ]; then
	echo "Decomb params: $decomb_params"
fi
echo "x264 options: $_x264_options"
echo '*******************************************************************************'
echo
set -x

# Should we suggest a config update?
test -z "$config_version" && config_version=0
if [ $hb_config_version -gt $config_version ]; then
	set +x
	echo '*******************************************************************************'
	echo "WARNING: hb configuration version is newer than the one you're using,"
	echo "you may want to re-scaffold."
	echo '*******************************************************************************'
	set -x
fi

# handle subtitles
for _subtitle in $subtitles; do
	_sid=$(($_subtitle - 1))
	_track=$((20 + $_sid))
	_track="0x${_track}"


	# (dvd_reader.c) subtitle 00=<en> 
	# (dvd_reader.c) subtitle 01=<es> 
	# (dvd_reader.c) subtitle 02=<es> 
	# (dvd_reader.c) subtitle 03=<fr> 
	_sid_padded=`printf '%02d' $_sid`
	_lang=`tcprobe -i "$dvd_source" 2>&1 | grep " subtitle ${_sid_padded}=" | sed -r 's,.*=<([^>]+)>[ 	]*,\1,'`

	cp "${dvd_source}/VIDEO_TS/VTS_01_0.IFO" "subtitles_${_sid}.ifo"

	if [ -z "$chapters" ]; then
		tccat -i "$dvd_source" -T "$title",-1 | \
		tcextract -x ps1 -t vob -a "$_track" | \
		subtitle2vobsub	-i "subtitles_${_sid}.ifo" \
				-o "subtitles_${_sid}"
	else
		rm -rf chapters
		mkdir chapters
		for _chapter in $chapters; do
			tccat -i "$dvd_source" \
			      -T "$title",${_chapter} > chapters/${_chapter}.vob
		done

		tccat -i chapters | \
		tcextract -x ps1 -t vob -a "$_track" | \
		subtitle2vobsub	-i "subtitles_${_sid}.ifo" \
				-o "subtitles_${_sid}"

		rm -rf chapters
	fi

	perl -pi -e "s/^id: /id: ${_lang}/" "subtitles_${_sid}.idx"
done

HandBrakeCLI	-i "$dvd_source" \
		-f "${output_format}" \
		-o "${output}.${output_format}" \
		-t "$title" \
		-e x264 \
		"$_anamorphic_arg" \
		-a "$_audio_tracks" -E "$_audio_encoder" \
		-B "$_audio_bitrate" \
		-q "$quality" \
		"$_chapter_arg" \
		"$_grayscale_arg" \
		"$_deinterlace_arg" \
		"$_decomb_arg" \
		-x "$_x264_options"

#
# If we're writing an AVI file, build an index so players and play it and
# mkvmerge can mux it into an MKV container.
#
if [ "$output_format" = 'avi' ]; then
	aviindex -i "${output}.${output_format}" \
	         -o "${output}.aviindex"
	avimerge -i "${output}.${output_format}" \
	         -o "${output}-merged.${output_format}" \
	         -x "${output}.aviindex"
	rm -f "${output}.aviindex"
	mv "${output}-merged.${output_format}" \
	   "${output}.${output_format}"
fi
